name: pre-merge
run-name: ${{ github.actor }} pre-merge checks
on: [pull_request]

jobs:
  run-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: false
          installer-parallel: true
      - run: poetry install
      - run: pip install --upgrade "jax[cpu]"
      - run: pytest -vvs

  run-linting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: false
          installer-parallel: true
      - run: poetry install
      - run: pre-commit install
      - run: task lint

  build-package:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: false
          installer-parallel: true
      - run: poetry install
      - run: poetry build
      - run: echo "VERSION=$(poetry version --short)" >> $GITHUB_ENV
      - run: ls dist
